name: Auto update pipeline for python app

on:
    push:
        branches:
            '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        # - name: install required pip
        #   run: |
        #     sudo apt update
        #     sudo apt install python3-pip
        #     pip3 install pytest    

        # - name: Run tests
        #   run: |
        #     pytest
        - name: Login to docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Build and push to Docker hub
          uses: docker/build-push-action@v2
          with:
            context: .
            push: True
            tags: shravan2134/my_python_app:latest